import "./globals.css";
import { Navigation } from "~/components";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <title>Viloria Dev</title>
      <body className="flex flex-col min-h-screen">
        <Navigation />
        <div className="w-full min-h-screen flex flex-col bg-gradient-to-r from-slate-900 to-slate-950 relative">
          <div className="flex w-full flex-col justify-center text-white">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
