import "./globals.css";
import { Navigation } from "~/components";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <title>Viloria Dev</title>
      <body className="flex flex-col items-center min-h-screen px-4">
        <div className="max-w-[80rem] w-full min-h-screen flex flex-col justify-center relative">
          <Navigation />
          {children}
        </div>
      </body>
    </html>
  );
}
